"""
Zoho CRM API Client Library
Generated by Agent 1 - Project Setup & OAuth Specialist

This package provides a complete Python client for Zoho CRM API v8,
designed for use with MCP (Model Context Protocol) servers.
"""

__version__ = "1.0.0"
__author__ = "Medical Travel Colombia - ThinkFlowLabs"

from .auth import ZohoAuth

__all__ = ["ZohoAuth"]
