"""
Zoho CRM Activities API Client (Tasks, Events, Calls)
Generated by Agent 5 - Activities & Notes Specialist

Handles Task, Event, and Call operations with proper linking to other modules.
"""

import logging
from typing import Any, Dict, List, Optional
from .base_client import ZohoBaseClient

logger = logging.getLogger(__name__)


class ZohoActivities(ZohoBaseClient):
    """
    Client for Zoho CRM Activities (Tasks, Events, Calls).

    Supports:
    - Creating tasks linked to Leads/Contacts/Deals
    - Creating events (meetings)
    - Creating calls
    - Getting activities for a specific record

    Usage:
        client = ZohoActivities()
        task = await client.create_task(
            subject="Follow up",
            what_id="123456",  # Lead/Contact/Deal ID
            due_date="2024-01-15"
        )
    """

    async def create_task(
        self,
        subject: str,
        what_id: Optional[str] = None,
        who_id: Optional[str] = None,
        due_date: Optional[str] = None,
        status: str = "Not Started",
        priority: str = "Normal",
        description: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Create a new task.

        Args:
            subject: Task subject (required)
            what_id: Related record ID (Lead, Contact, Deal, Account)
            who_id: Contact or Lead ID
            due_date: Due date in format "YYYY-MM-DD"
            status: Task status (Not Started, In Progress, Completed, etc.)
            priority: Priority level (High, Normal, Low)
            description: Task description

        Returns:
            Dict: Response with task ID

        Example:
            >>> await client.create_task(
            ...     subject="Follow up call",
            ...     what_id="123456",  # Lead ID
            ...     due_date="2024-01-15",
            ...     priority="High"
            ... )
        """
        data = {
            "Subject": subject,
            "Status": status,
            "Priority": priority
        }

        if what_id:
            data["What_Id"] = what_id
        if who_id:
            data["Who_Id"] = who_id
        if due_date:
            data["Due_Date"] = due_date
        if description:
            data["Description"] = description

        payload = {"data": [data]}
        response = await self.post("/Tasks", data=payload)
        return response

    async def get_task(self, task_id: str) -> Dict[str, Any]:
        """
        Get a task by ID.

        Args:
            task_id: Task ID

        Returns:
            Dict: Task data
        """
        return await self.get(f"/Tasks/{task_id}")

    async def get_tasks_for_record(
        self,
        module: str,
        record_id: str,
        page: int = 1,
        per_page: int = 200
    ) -> Dict[str, Any]:
        """
        Get all tasks related to a specific record.

        Args:
            module: Module name (Leads, Contacts, Deals, Accounts)
            record_id: Record ID
            page: Page number
            per_page: Records per page

        Returns:
            Dict: List of tasks

        Example:
            >>> await client.get_tasks_for_record("Leads", "123456")
        """
        params = {"page": page, "per_page": min(per_page, 200)}
        return await self.get(f"/{module}/{record_id}/Tasks", params=params)

    async def update_task(
        self,
        task_id: str,
        data: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Update a task.

        Args:
            task_id: Task ID
            data: Fields to update

        Returns:
            Dict: Response

        Example:
            >>> await client.update_task("789", {"Status": "Completed"})
        """
        payload = {"data": [data]}
        return await self.put(f"/Tasks/{task_id}", data=payload)

    async def delete_task(self, task_id: str) -> Dict[str, Any]:
        """Delete a task."""
        return await self.delete(f"/Tasks/{task_id}")

    async def create_event(
        self,
        event_title: str,
        start_datetime: str,
        end_datetime: str,
        what_id: Optional[str] = None,
        who_id: Optional[str] = None,
        venue: Optional[str] = None,
        description: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Create a new event (meeting).

        Args:
            event_title: Event title (required)
            start_datetime: Start date/time "YYYY-MM-DD HH:MM:SS"
            end_datetime: End date/time "YYYY-MM-DD HH:MM:SS"
            what_id: Related record ID
            who_id: Contact or Lead ID
            venue: Event location
            description: Event description

        Returns:
            Dict: Response with event ID

        Example:
            >>> await client.create_event(
            ...     event_title="Product Demo",
            ...     start_datetime="2024-01-15 10:00:00",
            ...     end_datetime="2024-01-15 11:00:00",
            ...     what_id="123456"
            ... )
        """
        data = {
            "Event_Title": event_title,
            "Start_DateTime": start_datetime,
            "End_DateTime": end_datetime
        }

        if what_id:
            data["What_Id"] = what_id
        if who_id:
            data["Who_Id"] = who_id
        if venue:
            data["Venue"] = venue
        if description:
            data["Description"] = description

        payload = {"data": [data]}
        return await self.post("/Events", data=payload)

    async def get_event(self, event_id: str) -> Dict[str, Any]:
        """Get an event by ID."""
        return await self.get(f"/Events/{event_id}")

    async def get_events_for_record(
        self,
        module: str,
        record_id: str
    ) -> Dict[str, Any]:
        """Get all events for a record."""
        return await self.get(f"/{module}/{record_id}/Events")

    async def update_event(
        self,
        event_id: str,
        data: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Update an event."""
        payload = {"data": [data]}
        return await self.put(f"/Events/{event_id}", data=payload)

    async def delete_event(self, event_id: str) -> Dict[str, Any]:
        """Delete an event."""
        return await self.delete(f"/Events/{event_id}")

    async def create_call(
        self,
        subject: str,
        call_type: str,
        call_start_time: str,
        call_duration: str,
        what_id: Optional[str] = None,
        who_id: Optional[str] = None,
        description: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Create a call log.

        Args:
            subject: Call subject
            call_type: "Outbound" or "Inbound"
            call_start_time: Start time "YYYY-MM-DD HH:MM:SS"
            call_duration: Duration in format "HH:MM:SS" (e.g., "00:15:00" for 15 min)
            what_id: Related record ID
            who_id: Contact or Lead ID
            description: Call notes

        Returns:
            Dict: Response with call ID

        Example:
            >>> await client.create_call(
            ...     subject="Discovery call",
            ...     call_type="Outbound",
            ...     call_start_time="2024-01-15 14:00:00",
            ...     call_duration="00:30:00",
            ...     what_id="123456"
            ... )
        """
        data = {
            "Subject": subject,
            "Call_Type": call_type,
            "Call_Start_Time": call_start_time,
            "Call_Duration": call_duration
        }

        if what_id:
            data["What_Id"] = what_id
        if who_id:
            data["Who_Id"] = who_id
        if description:
            data["Description"] = description

        payload = {"data": [data]}
        return await self.post("/Calls", data=payload)

    async def get_call(self, call_id: str) -> Dict[str, Any]:
        """Get a call by ID."""
        return await self.get(f"/Calls/{call_id}")

    async def update_call(
        self,
        call_id: str,
        data: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Update a call."""
        payload = {"data": [data]}
        return await self.put(f"/Calls/{call_id}", data=payload)

    async def delete_call(self, call_id: str) -> Dict[str, Any]:
        """Delete a call."""
        return await self.delete(f"/Calls/{call_id}")
