"""
Zoho OAuth 2.0 Authentication Handler
Generated by Agent 1 - Project Setup & OAuth Specialist

Handles OAuth token management, refresh, and validation for Zoho CRM API.
"""

import os
import logging
from typing import Optional
from datetime import datetime, timedelta
import asyncio
import httpx
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

logger = logging.getLogger(__name__)


class ZohoAuth:
    """
    Manages Zoho CRM OAuth 2.0 authentication.

    Automatically handles:
    - Access token generation
    - Token refresh when expired
    - Token caching
    - Error handling

    Usage:
        auth = ZohoAuth()
        token = await auth.get_access_token()
    """

    def __init__(self):
        """Initialize Zoho OAuth client with credentials from environment."""
        self.client_id = os.getenv("ZOHO_CLIENT_ID")
        self.client_secret = os.getenv("ZOHO_CLIENT_SECRET")
        self.refresh_token = os.getenv("ZOHO_REFRESH_TOKEN")
        self.accounts_domain = os.getenv("ZOHO_ACCOUNTS_DOMAIN", "https://accounts.zoho.com")

        # Token cache
        self._access_token: Optional[str] = None
        self._token_expires_at: Optional[datetime] = None

        # Lock to prevent concurrent token refreshes
        self._refresh_lock = asyncio.Lock()

        # Validate configuration
        self._validate_config()

    def _validate_config(self) -> None:
        """Validate that all required credentials are present."""
        missing = []

        if not self.client_id:
            missing.append("ZOHO_CLIENT_ID")
        if not self.client_secret:
            missing.append("ZOHO_CLIENT_SECRET")
        if not self.refresh_token:
            missing.append("ZOHO_REFRESH_TOKEN")

        if missing:
            raise ValueError(
                f"Missing required Zoho credentials: {', '.join(missing)}. "
                f"Please check your .env file."
            )

    async def get_access_token(self) -> str:
        """
        Get a valid access token, refreshing if necessary.
        Uses a lock to prevent concurrent refresh requests.

        Returns:
            str: Valid Zoho CRM access token

        Raises:
            httpx.HTTPError: If token refresh fails
        """
        # Check if we have a valid cached token (outside lock for performance)
        if self._is_token_valid():
            logger.debug("Using cached access token")
            return self._access_token

        # Use lock to prevent concurrent refreshes
        async with self._refresh_lock:
            # Double-check after acquiring lock (another task might have refreshed)
            if self._is_token_valid():
                logger.debug("Token was refreshed by another task, using cached token")
                return self._access_token

            # Token expired or not present, refresh it
            logger.info("Access token expired or missing, refreshing...")
            return await self._refresh_access_token()

    def _is_token_valid(self) -> bool:
        """
        Check if the cached token is still valid.

        Returns:
            bool: True if token exists and hasn't expired
        """
        if not self._access_token or not self._token_expires_at:
            return False

        # Add 60 second buffer to avoid edge cases
        return datetime.now() < (self._token_expires_at - timedelta(seconds=60))

    async def _refresh_access_token(self) -> str:
        """
        Refresh the access token using the refresh token.

        Returns:
            str: New access token

        Raises:
            httpx.HTTPError: If refresh request fails
            ValueError: If response doesn't contain access token
        """
        url = f"{self.accounts_domain}/oauth/v2/token"

        params = {
            "refresh_token": self.refresh_token,
            "client_id": self.client_id,
            "client_secret": self.client_secret,
            "grant_type": "refresh_token"
        }

        try:
            async with httpx.AsyncClient() as client:
                logger.info(f"Requesting token refresh from {url}")
                response = await client.post(url, params=params, timeout=30.0)

                # Log the raw response for debugging
                logger.info(f"Token refresh response status: {response.status_code}")
                logger.debug(f"Token refresh response body: {response.text}")

                # Check for HTTP errors
                if response.status_code != 200:
                    error_text = response.text
                    logger.error(f"Token refresh failed with status {response.status_code}: {error_text}")

                    # Try to parse error response
                    try:
                        error_data = response.json()
                        error_msg = error_data.get("error", "Unknown error")
                        error_desc = error_data.get("error_description", "No description")
                        raise ValueError(f"Zoho OAuth error: {error_msg} - {error_desc}")
                    except:
                        raise ValueError(f"Token refresh failed: HTTP {response.status_code} - {error_text}")

                # Parse successful response
                try:
                    data = response.json()
                except Exception as e:
                    logger.error(f"Failed to parse JSON response: {response.text}")
                    raise ValueError(f"Invalid JSON response from Zoho: {e}")

                # Log the parsed response (without sensitive data in production)
                logger.debug(f"Token refresh parsed data keys: {list(data.keys())}")

                # Extract token and expiry
                self._access_token = data.get("access_token")
                expires_in = data.get("expires_in", 3600)  # Default 1 hour

                if not self._access_token:
                    error_msg = f"No access_token in response. Available keys: {list(data.keys())}, Response: {data}"
                    logger.error(error_msg)
                    raise ValueError(error_msg)

                # Calculate expiry time
                self._token_expires_at = datetime.now() + timedelta(seconds=expires_in)

                logger.info(f"✅ Access token refreshed successfully (expires in {expires_in}s)")
                return self._access_token

        except httpx.TimeoutException as e:
            logger.error(f"Timeout during token refresh: {e}")
            raise ValueError(f"Token refresh timeout: {e}")
        except httpx.HTTPError as e:
            logger.error(f"HTTP error during token refresh: {e}")
            raise ValueError(f"HTTP error during token refresh: {e}")
        except ValueError:
            # Re-raise ValueError as-is
            raise
        except Exception as e:
            logger.error(f"Unexpected error during token refresh: {type(e).__name__}: {e}")
            raise ValueError(f"Unexpected error during token refresh: {e}")

    async def validate_token(self) -> bool:
        """
        Validate the current access token by making a test API call.

        Returns:
            bool: True if token is valid
        """
        try:
            token = await self.get_access_token()

            # Test token with a simple API call
            api_domain = os.getenv("ZOHO_API_DOMAIN", "https://www.zohoapis.com")
            test_url = f"{api_domain}/crm/v8/settings/modules"

            async with httpx.AsyncClient() as client:
                response = await client.get(
                    test_url,
                    headers={"Authorization": f"Zoho-oauthtoken {token}"},
                    timeout=10.0
                )

                return response.status_code == 200

        except Exception as e:
            logger.error(f"Token validation failed: {e}")
            return False

    def get_auth_header(self, token: str) -> dict:
        """
        Generate authorization header for Zoho API requests.

        Args:
            token: Access token

        Returns:
            dict: Headers dictionary with authorization
        """
        return {"Authorization": f"Zoho-oauthtoken {token}"}

    async def revoke_token(self) -> bool:
        """
        Revoke the current refresh token (logout).

        Returns:
            bool: True if revocation successful
        """
        url = f"{self.accounts_domain}/oauth/v2/token/revoke"

        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    url,
                    params={"token": self.refresh_token},
                    timeout=10.0
                )

                success = response.status_code == 200

                if success:
                    self._access_token = None
                    self._token_expires_at = None
                    logger.info("Token revoked successfully")

                return success

        except Exception as e:
            logger.error(f"Failed to revoke token: {e}")
            return False


# Singleton instance for easy access
_auth_instance: Optional[ZohoAuth] = None


def get_auth() -> ZohoAuth:
    """
    Get the singleton ZohoAuth instance.

    Returns:
        ZohoAuth: Shared authentication instance
    """
    global _auth_instance

    if _auth_instance is None:
        _auth_instance = ZohoAuth()

    return _auth_instance
