"""
Zoho CRM Metadata & Configuration APIs Client
Generated by Subagent-4 - Metadata & Configuration APIs Implementation

Handles metadata operations for fields, layouts, templates, and tags.
"""

import logging
from typing import Any, Dict, List, Optional
from .base_client import ZohoBaseClient
from .utils import clean_zoho_response, format_error_message

logger = logging.getLogger(__name__)


class ZohoMetadata(ZohoBaseClient):
    """
    Client for Zoho CRM Metadata and Configuration operations.

    Supports:
    - Field Management (get, update, delete custom fields)
    - Layout Management (get, update, delete custom layouts)
    - Inventory Templates (list and get templates)
    - Tag Management (list and search tags)

    OAuth Scopes Required:
    - ZohoCRM.settings.ALL
    - ZohoCRM.settings.fields.* (for field operations)
    - ZohoCRM.settings.layouts.* (for layout operations)
    - ZohoCRM.settings.tags.* (for tag operations)
    - ZohoCRM.templates.inventory.READ (for template operations)

    Usage:
        client = ZohoMetadata()
        fields = await client.get_field_metadata("Leads")
    """

    # ============================================================================
    # FIELD MANAGEMENT METHODS
    # ============================================================================

    async def get_field_metadata(
        self,
        module: str,
        field_id: Optional[str] = None,
        field_type: str = "all",
        include_permissions: bool = False
    ) -> Dict[str, Any]:
        """
        Get field metadata for a module or specific field.

        OAuth Scopes:
        - ZohoCRM.settings.fields.READ
        - ZohoCRM.settings.fields.ALL
        - ZohoCRM.settings.ALL

        Args:
            module: Module API name (e.g., "Leads", "Contacts")
            field_id: Optional field ID to get specific field details
            field_type: "all" (default) or "unused"
            include_permissions: Include allowed permissions to update

        Returns:
            Dict: Field metadata including labels, data types, picklist values, etc.

        Example:
            >>> # Get all fields for Leads module
            >>> fields = await client.get_field_metadata("Leads")

            >>> # Get specific field by ID
            >>> field = await client.get_field_metadata("Leads", field_id="123456789")

            >>> # Get only unused fields
            >>> unused = await client.get_field_metadata("Leads", field_type="unused")
        """
        params = {"module": module}

        if field_type != "all":
            params["type"] = field_type

        if include_permissions:
            params["include"] = "allowed_permissions_to_update"

        # Specific field or all fields
        endpoint = f"/settings/fields/{field_id}" if field_id else "/settings/fields"

        response = await self.get(endpoint, params=params)
        return response

    async def update_custom_field(
        self,
        module: str,
        field_id: str,
        updates: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Update custom field settings.

        OAuth Scopes:
        - ZohoCRM.settings.fields.UPDATE
        - ZohoCRM.settings.fields.ALL
        - ZohoCRM.settings.ALL

        IMPORTANT RESTRICTIONS:
        - Maximum 5 fields can be updated per API call
        - Cannot update system-defined fields
        - Cannot change field data type
        - Field API names must start with alphabet, contain only alphanumeric and underscore
        - External attributes cannot be updated

        Supported Updates:
        - Picklist values (add/reorder)
        - Rollup summary fields
        - Dynamic formula fields
        - Convert local to global picklist
        - History tracking for picklist fields
        - Field labels (custom fields only)
        - Required/filterable/searchable attributes

        Args:
            module: Module API name
            field_id: Field ID to update
            updates: Field updates (e.g., {"field_label": "New Label", "filterable": true})

        Returns:
            Dict: Update status

        Example:
            >>> # Update field label
            >>> await client.update_custom_field("Leads", "123456789", {
            ...     "field_label": "Customer Type"
            ... })

            >>> # Update picklist values
            >>> await client.update_custom_field("Leads", "123456789", {
            ...     "pick_list_values": [
            ...         {"display_value": "Option 1", "actual_value": "opt1"},
            ...         {"display_value": "Option 2", "actual_value": "opt2"}
            ...     ]
            ... })
        """
        params = {"module": module}
        payload = {"fields": [updates]}

        response = await self._request(
            "PATCH",
            f"/settings/fields/{field_id}",
            json=payload,
            params=params
        )
        return response

    async def delete_custom_field(
        self,
        module: str,
        field_id: str
    ) -> Dict[str, Any]:
        """
        Delete a custom field from a module.

        OAuth Scopes:
        - ZohoCRM.settings.fields.DELETE
        - ZohoCRM.settings.fields.ALL
        - ZohoCRM.settings.ALL

        IMPORTANT RESTRICTIONS:
        - Only custom fields can be deleted
        - One custom field per API call
        - Cannot delete fields used in:
            * Workflows
            * Scoring rules
            * Approval processes
            * Custom views
            * Email templates
            * Assignment rules
            * Validation rules

        Args:
            module: Module API name
            field_id: Field ID to delete

        Returns:
            Dict: Deletion status

        Example:
            >>> result = await client.delete_custom_field("Leads", "123456789")
            >>> print(result)
            {"fields": [{"code": "SUCCESS", "message": "field deleted"}]}
        """
        params = {"module": module}

        response = await self.delete(f"/settings/fields/{field_id}", params=params)
        return response

    # ============================================================================
    # LAYOUT MANAGEMENT METHODS
    # ============================================================================

    async def get_layouts(
        self,
        module: str
    ) -> Dict[str, Any]:
        """
        Get all layouts for a module.

        OAuth Scopes:
        - ZohoCRM.settings.layouts.READ
        - ZohoCRM.settings.layouts.ALL
        - ZohoCRM.settings.ALL

        Supported Modules:
        - Leads, Accounts, Contacts, Deals, Campaigns, Tasks, Cases
        - Events, Calls, Solutions, Products, Vendors, Price Books
        - Quotes, Sales Orders, Purchase Orders, Invoices
        - Appointments, Services, Custom modules

        Args:
            module: Module API name

        Returns:
            Dict: All layouts with sections and fields

        Example:
            >>> layouts = await client.get_layouts("Leads")
            >>> for layout in layouts["layouts"]:
            ...     print(f"Layout: {layout['name']}")
        """
        params = {"module": module}
        response = await self.get("/settings/layouts", params=params)
        return response

    async def get_layout_by_id(
        self,
        module: str,
        layout_id: str
    ) -> Dict[str, Any]:
        """
        Get a specific layout by ID.

        OAuth Scopes:
        - ZohoCRM.settings.layouts.READ
        - ZohoCRM.settings.layouts.ALL
        - ZohoCRM.settings.ALL

        Args:
            module: Module API name
            layout_id: Layout ID

        Returns:
            Dict: Layout details with sections, fields, and configuration

        Example:
            >>> layout = await client.get_layout_by_id("Leads", "987654321")
        """
        params = {"module": module}
        response = await self.get(f"/settings/layouts/{layout_id}", params=params)
        return response

    async def update_custom_layout(
        self,
        module: str,
        layout_id: str,
        updates: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Update a custom layout configuration.

        OAuth Scopes:
        - ZohoCRM.settings.layouts.UPDATE
        - ZohoCRM.settings.layouts.ALL
        - ZohoCRM.settings.ALL

        IMPORTANT CONSTRAINTS:
        - Maximum 5 field actions per API call
        - Maximum 5 sections per call
        - Maximum 2 unique fields per module
        - Maximum 1 auto-number field per module

        Args:
            module: Module API name
            layout_id: Layout ID to update
            updates: Layout updates (sections, fields, etc.)

        Returns:
            Dict: Update status

        Example:
            >>> await client.update_custom_layout("Leads", "987654321", {
            ...     "name": "Updated Layout Name",
            ...     "sections": [...]
            ... })
        """
        params = {"module": module}
        payload = {"layouts": [updates]}

        response = await self._request(
            "PATCH",
            f"/settings/layouts/{layout_id}",
            json=payload,
            params=params
        )
        return response

    async def delete_custom_layout(
        self,
        module: str,
        layout_id: str,
        transfer_to: str
    ) -> Dict[str, Any]:
        """
        Delete a custom layout and transfer records to another layout.

        OAuth Scopes:
        - ZohoCRM.settings.layouts.DELETE
        - ZohoCRM.settings.layouts.ALL
        - ZohoCRM.settings.ALL

        IMPORTANT CONSTRAINTS:
        - One custom layout per API call
        - Only custom layouts can be deleted (not system default)
        - Must transfer records to an active layout
        - transfer_to parameter is MANDATORY

        Args:
            module: Module API name
            layout_id: Layout ID to delete
            transfer_to: Layout ID to transfer existing records to (required)

        Returns:
            Dict: Deletion status

        Example:
            >>> # Delete layout and transfer records to default layout
            >>> await client.delete_custom_layout(
            ...     "Leads",
            ...     layout_id="123456789",
            ...     transfer_to="987654321"
            ... )
        """
        params = {
            "module": module,
            "transfer_to": transfer_to
        }

        response = await self.delete(f"/settings/layouts/{layout_id}", params=params)
        return response

    # ============================================================================
    # INVENTORY TEMPLATE METHODS
    # ============================================================================

    async def get_inventory_templates(
        self,
        module: Optional[str] = None,
        category: Optional[str] = None,
        sort_by: str = "modified_time",
        sort_order: str = "desc"
    ) -> Dict[str, Any]:
        """
        Get inventory templates (for Quotes, Invoices, Sales Orders, Purchase Orders).

        OAuth Scope:
        - ZohoCRM.templates.inventory.READ

        Supported Modules:
        - Quotes, Invoices, Purchase_Orders, Sales_Orders
        - Any module with "inventory_template_supported" = true

        Args:
            module: Optional module API name to filter templates
            category: Optional category filter:
                      - "favorite" - User's favorite templates
                      - "created_by_me" - Templates created by current user
                      - "shared_with_me" - Templates shared with current user
                      - "draft" - Draft templates
            sort_by: Sort field (default "modified_time", options: "last_usage_time", "name")
            sort_order: Sort order "asc" or "desc" (default "desc")

        Returns:
            Dict: List of inventory templates

        Example:
            >>> # Get all templates
            >>> templates = await client.get_inventory_templates()

            >>> # Get templates for specific module
            >>> quotes = await client.get_inventory_templates(module="Quotes")

            >>> # Get favorite templates
            >>> favorites = await client.get_inventory_templates(category="favorite")
        """
        params = {
            "sort_by": sort_by,
            "sort_order": sort_order
        }

        if module:
            params["module"] = module

        if category:
            params["category"] = category

        response = await self.get("/settings/inventory_templates", params=params)
        return response

    async def get_inventory_template_by_id(
        self,
        template_id: str
    ) -> Dict[str, Any]:
        """
        Get a specific inventory template by ID.

        OAuth Scope:
        - ZohoCRM.templates.inventory.READ

        Args:
            template_id: Template ID

        Returns:
            Dict: Template details including content, module, folder, etc.

        Example:
            >>> template = await client.get_inventory_template_by_id("123456789")
            >>> print(f"Template: {template['name']}")
            >>> print(f"Module: {template['module']['api_name']}")
        """
        response = await self.get(f"/settings/inventory_templates/{template_id}")
        return response

    # ============================================================================
    # TAG MANAGEMENT METHODS
    # ============================================================================

    async def get_tags_list(
        self,
        module: str,
        my_tags: bool = False
    ) -> Dict[str, Any]:
        """
        Get list of all tags for a module.

        OAuth Scopes:
        - ZohoCRM.settings.ALL
        - ZohoCRM.settings.tags.READ
        - ZohoCRM.settings.tags.ALL

        Edition-wise Tag Limits:
        - Module-wise Tag Creation: 20-200 tags (varies by edition)
        - Record-wise Tag Creation: 5-10 tags (varies by edition)

        Args:
            module: Module API name (mandatory)
            my_tags: If True, only return tags created by current user (default False)

        Returns:
            Dict: List of tags with IDs, names, colors, timestamps

        Example:
            >>> # Get all tags for Leads
            >>> tags = await client.get_tags_list("Leads")

            >>> # Get only my tags
            >>> my_tags = await client.get_tags_list("Leads", my_tags=True)
        """
        params = {"module": module}

        if my_tags:
            params["my_tags"] = "true"

        response = await self.get("/settings/tags", params=params)
        return response

    async def get_tags_for_module(
        self,
        module: str
    ) -> List[Dict[str, Any]]:
        """
        Get tags specific to a module (convenience method with cleaner output).

        Args:
            module: Module API name

        Returns:
            List[Dict]: List of tag dictionaries with simplified structure

        Example:
            >>> tags = await client.get_tags_for_module("Leads")
            >>> for tag in tags:
            ...     print(f"{tag['name']} (ID: {tag['id']})")
        """
        response = await self.get_tags_list(module)

        # Extract and simplify tag data
        if response.get("tags"):
            return [
                {
                    "id": tag.get("id"),
                    "name": tag.get("name"),
                    "colour_code": tag.get("colour_code"),
                    "created_time": tag.get("created_time")
                }
                for tag in response["tags"]
            ]

        return []

    # ============================================================================
    # HELPER METHODS FOR FORMATTING RESPONSES
    # ============================================================================

    def format_field_summary(self, field_data: Dict[str, Any]) -> str:
        """
        Format field metadata into a readable summary.

        Args:
            field_data: Field metadata from get_field_metadata()

        Returns:
            str: Formatted field summary
        """
        if not field_data.get("fields"):
            return "No fields found"

        output = []
        for field in field_data["fields"]:
            output.append(f"\n{'='*60}")
            output.append(f"Field: {field.get('field_label', 'N/A')}")
            output.append(f"API Name: {field.get('api_name', 'N/A')}")
            output.append(f"Data Type: {field.get('data_type', 'N/A')}")
            output.append(f"ID: {field.get('id', 'N/A')}")

            # Display custom field status
            if field.get("custom_field"):
                output.append("Custom Field: Yes")
            else:
                output.append("Custom Field: No (System)")

            # Display mandatory/required status
            if field.get("required"):
                output.append("Required: Yes")

            # Display picklist values if applicable
            if field.get("pick_list_values"):
                output.append("\nPicklist Values:")
                for option in field["pick_list_values"][:5]:  # Show first 5
                    output.append(f"  - {option.get('display_value', 'N/A')}")
                if len(field["pick_list_values"]) > 5:
                    output.append(f"  ... and {len(field['pick_list_values']) - 5} more")

            # Display lookup details if applicable
            if field.get("lookup"):
                lookup = field["lookup"]
                output.append(f"\nLookup Module: {lookup.get('module', {}).get('api_name', 'N/A')}")

        return "\n".join(output)

    def format_layout_summary(self, layout_data: Dict[str, Any]) -> str:
        """
        Format layout metadata into a readable summary.

        Args:
            layout_data: Layout data from get_layouts() or get_layout_by_id()

        Returns:
            str: Formatted layout summary
        """
        if not layout_data.get("layouts"):
            return "No layouts found"

        output = []
        for layout in layout_data["layouts"]:
            output.append(f"\n{'='*60}")
            output.append(f"Layout: {layout.get('name', 'N/A')}")
            output.append(f"ID: {layout.get('id', 'N/A')}")
            output.append(f"Visible: {layout.get('visible', False)}")
            output.append(f"Status: {layout.get('status', 'N/A')}")

            # Display sections
            if layout.get("sections"):
                output.append(f"\nSections ({len(layout['sections'])}):")
                for section in layout["sections"][:3]:  # Show first 3 sections
                    output.append(f"  - {section.get('display_label', 'N/A')}")
                    if section.get("fields"):
                        output.append(f"    Fields: {len(section['fields'])}")
                if len(layout["sections"]) > 3:
                    output.append(f"  ... and {len(layout['sections']) - 3} more sections")

        return "\n".join(output)

    def format_template_summary(self, template_data: Dict[str, Any]) -> str:
        """
        Format inventory template metadata into a readable summary.

        Args:
            template_data: Template data from get_inventory_templates()

        Returns:
            str: Formatted template summary
        """
        if not template_data.get("inventory_templates"):
            return "No templates found"

        output = []
        for template in template_data["inventory_templates"]:
            output.append(f"\n{'='*60}")
            output.append(f"Template: {template.get('name', 'N/A')}")
            output.append(f"ID: {template.get('id', 'N/A')}")

            if template.get("module"):
                output.append(f"Module: {template['module'].get('api_name', 'N/A')}")

            output.append(f"Category: {template.get('category', 'N/A')}")
            output.append(f"Editor Mode: {template.get('editor_mode', 'N/A')}")
            output.append(f"Favorite: {template.get('favorite', False)}")

            if template.get("last_usage_time"):
                output.append(f"Last Used: {template['last_usage_time']}")

        return "\n".join(output)

    def format_tags_summary(self, tags_data: Dict[str, Any]) -> str:
        """
        Format tags metadata into a readable summary.

        Args:
            tags_data: Tags data from get_tags_list()

        Returns:
            str: Formatted tags summary
        """
        if not tags_data.get("tags"):
            return "No tags found"

        output = [f"\nTotal Tags: {len(tags_data['tags'])}"]
        output.append(f"{'='*60}")

        for tag in tags_data["tags"]:
            output.append(f"\n{tag.get('name', 'N/A')}")
            output.append(f"  ID: {tag.get('id', 'N/A')}")
            output.append(f"  Color: {tag.get('colour_code', 'N/A')}")
            if tag.get("created_time"):
                output.append(f"  Created: {tag['created_time']}")

        return "\n".join(output)
