"""
Zoho CRM Notes API Client
Generated by Agent 5 - Activities & Notes Specialist

Handles Note operations - can attach notes to any module record.
"""

import logging
from typing import Any, Dict, Optional
from .base_client import ZohoBaseClient

logger = logging.getLogger(__name__)


class ZohoNotes(ZohoBaseClient):
    """
    Client for Zoho CRM Notes operations.

    Notes can be attached to any module:
    - Leads, Contacts, Accounts, Deals
    - Products, Quotes, etc.

    Usage:
        client = ZohoNotes()
        note = await client.create_note(
            module="Leads",
            record_id="123456",
            title="Meeting Notes",
            content="Discussed pricing..."
        )
    """

    async def create_note(
        self,
        module: str,
        record_id: str,
        title: str,
        content: str
    ) -> Dict[str, Any]:
        """
        Create a note attached to a record.

        Args:
            module: Module name (Leads, Contacts, Accounts, etc.)
            record_id: Record ID to attach note to
            title: Note title
            content: Note content

        Returns:
            Dict: Response with note ID

        Example:
            >>> await client.create_note(
            ...     module="Leads",
            ...     record_id="123456",
            ...     title="Follow-up Notes",
            ...     content="Customer interested in premium package"
            ... )
        """
        data = {
            "Note_Title": title,
            "Note_Content": content
        }

        payload = {"data": [data]}
        response = await self.post(f"/{module}/{record_id}/Notes", data=payload)
        return response

    async def get_notes(
        self,
        module: str,
        record_id: str,
        page: int = 1,
        per_page: int = 200
    ) -> Dict[str, Any]:
        """
        Get all notes for a record.

        Args:
            module: Module name
            record_id: Record ID
            page: Page number
            per_page: Records per page

        Returns:
            Dict: List of notes

        Example:
            >>> await client.get_notes("Leads", "123456")
        """
        params = {"page": page, "per_page": min(per_page, 200)}
        return await self.get(f"/{module}/{record_id}/Notes", params=params)

    async def get_note(
        self,
        module: str,
        record_id: str,
        note_id: str
    ) -> Dict[str, Any]:
        """
        Get a specific note.

        Args:
            module: Module name
            record_id: Record ID
            note_id: Note ID

        Returns:
            Dict: Note data
        """
        return await self.get(f"/{module}/{record_id}/Notes/{note_id}")

    async def update_note(
        self,
        module: str,
        record_id: str,
        note_id: str,
        title: Optional[str] = None,
        content: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Update a note.

        Args:
            module: Module name
            record_id: Record ID
            note_id: Note ID
            title: New title (optional)
            content: New content (optional)

        Returns:
            Dict: Response

        Example:
            >>> await client.update_note(
            ...     module="Leads",
            ...     record_id="123456",
            ...     note_id="789",
            ...     content="Updated: Customer confirmed interest"
            ... )
        """
        data = {}
        if title:
            data["Note_Title"] = title
        if content:
            data["Note_Content"] = content

        payload = {"data": [data]}
        return await self.put(f"/{module}/{record_id}/Notes/{note_id}", data=payload)

    async def delete_note(
        self,
        module: str,
        record_id: str,
        note_id: str
    ) -> Dict[str, Any]:
        """
        Delete a note.

        Args:
            module: Module name
            record_id: Record ID
            note_id: Note ID

        Returns:
            Dict: Response
        """
        return await self.delete(f"/{module}/{record_id}/Notes/{note_id}")
