"""
Zoho CRM Search API Client
Generated by Agent 6 - Search & Query Specialist

Handles all search operations with automatic datetime conversion.
"""

import logging
from typing import Any, Dict, List, Optional
from .base_client import ZohoBaseClient
from .utils import build_zoho_criteria, format_datetime_for_zoho

logger = logging.getLogger(__name__)


class ZohoSearch(ZohoBaseClient):
    """
    Client for Zoho CRM Search operations.

    Supports:
    - Criteria-based search
    - Email search
    - Phone search
    - Word search

    Automatically handles datetime conversion for search criteria.

    Usage:
        client = ZohoSearch()
        results = await client.search_by_criteria(
            module="Leads",
            criteria="(Last_Name:equals:Smith)",
            fields=["First_Name", "Last_Name", "Email"]
        )
    """

    async def search_by_criteria(
        self,
        module: str,
        criteria: str,
        fields: Optional[List[str]] = None,
        page: int = 1,
        per_page: int = 200
    ) -> Dict[str, Any]:
        """
        Search records using criteria string.

        Args:
            module: Module to search (Leads, Contacts, etc.)
            criteria: Search criteria in Zoho format
                Examples:
                - "(Last_Name:equals:Smith)"
                - "((Last_Name:contains:Smith)and(Email:contains:@gmail.com))"
            fields: Fields to return (None for defaults)
            page: Page number
            per_page: Records per page (max 200)

        Returns:
            Dict: Search results with data and pagination info

        Example:
            >>> await client.search_by_criteria(
            ...     module="Leads",
            ...     criteria="(Lead_Status:equals:Qualified)",
            ...     fields=["First_Name", "Last_Name", "Email"]
            ... )
        """
        params = {
            "criteria": criteria,
            "page": page,
            "per_page": min(per_page, 200)
        }

        if fields:
            params["fields"] = ",".join(fields)

        response = await self.get(f"/{module}/search", params=params)
        return response

    async def search_by_conditions(
        self,
        module: str,
        conditions: Dict[str, Any],
        fields: Optional[List[str]] = None,
        page: int = 1,
        per_page: int = 200
    ) -> Dict[str, Any]:
        """
        Search using dictionary of conditions (easier for AI).

        Automatically builds criteria string and converts datetime fields.

        Args:
            module: Module to search
            conditions: Dict of field: value or field__operator: value
                Examples:
                {
                    "Last_Name": "Smith",  # equals
                    "Email__contains": "@gmail.com",
                    "Created_Time__greater_than": "2024-01-01"  # auto-converted
                }
            fields: Fields to return
            page: Page number
            per_page: Records per page

        Returns:
            Dict: Search results

        Example:
            >>> await client.search_by_conditions(
            ...     module="Leads",
            ...     conditions={
            ...         "Last_Name": "Smith",
            ...         "Email__contains": "@gmail.com",
            ...         "Created_Time__greater_than": "2024-01-01"
            ...     }
            ... )
        """
        # Build criteria string with automatic datetime conversion
        criteria = build_zoho_criteria(conditions)

        return await self.search_by_criteria(
            module=module,
            criteria=criteria,
            fields=fields,
            page=page,
            per_page=per_page
        )

    async def search_by_email(
        self,
        module: str,
        email: str,
        fields: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Search records by email address.

        Searches across all email fields in the module.

        Args:
            module: Module to search
            email: Email address to search for
            fields: Fields to return

        Returns:
            Dict: Search results

        Example:
            >>> await client.search_by_email("Leads", "john@example.com")
        """
        params = {"email": email}

        if fields:
            params["fields"] = ",".join(fields)

        response = await self.get(f"/{module}/search", params=params)
        return response

    async def search_by_phone(
        self,
        module: str,
        phone: str,
        fields: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Search records by phone number.

        Searches across all phone fields in the module.

        Args:
            module: Module to search
            phone: Phone number to search for
            fields: Fields to return

        Returns:
            Dict: Search results

        Example:
            >>> await client.search_by_phone("Leads", "+1234567890")
        """
        params = {"phone": phone}

        if fields:
            params["fields"] = ",".join(fields)

        response = await self.get(f"/{module}/search", params=params)
        return response

    async def search_by_word(
        self,
        module: str,
        word: str,
        fields: Optional[List[str]] = None,
        page: int = 1,
        per_page: int = 200
    ) -> Dict[str, Any]:
        """
        Global word search across multiple fields.

        Args:
            module: Module to search
            word: Search term
            fields: Fields to return
            page: Page number (default: 1)
            per_page: Records per page (max 200)

        Returns:
            Dict: Search results

        Example:
            >>> await client.search_by_word("Leads", "Acme Corporation")
        """
        params = {
            "word": word,
            "page": page,
            "per_page": min(per_page, 200)
        }

        if fields:
            params["fields"] = ",".join(fields)

        response = await self.get(f"/{module}/search", params=params)
        return response

    async def search_by_coql(
        self,
        query: str,
        page: int = 1,
        per_page: int = 200
    ) -> Dict[str, Any]:
        """
        Execute a Zoho CRM Query Language (COQL) query.

        Args:
            query: The COQL query string (e.g., "SELECT * FROM Tasks WHERE Due_Date BETWEEN '2025-10-01' AND '2025-10-31'")
            page: Page number (default: 1)
            per_page: Records per page (max 200)

        Returns:
            Dict: Query results

        Example:
            >>> await client.search_by_coql("SELECT id, Subject, Due_Date FROM Tasks WHERE Status = 'Not Started'")
        """
        payload = {
            "select_query": query
        }
        response = await self.post("/coql", data=payload)
        return response

    def format_search_results(
        self,
        response: Dict[str, Any],
        module: str
    ) -> str:
        """
        Format search results into human-readable text.

        Args:
            response: Raw search response
            module: Module that was searched

        Returns:
            str: Formatted results

        Example output:
            Found 3 lead(s):

            1. John Smith
               Email: john@example.com
               Phone: +1234567890
               Company: Acme Inc
               ID: 123456

            2. Jane Doe
               ...
        """
        if not response.get("data"):
            return f"No {module.lower()} found matching criteria"

        records = response["data"]
        info = response.get("info", {})

        output = f"Found {len(records)} {module.lower()}(s)"

        if info.get("more_records"):
            output += f" (page {info.get('page', 1)} of many)"

        output += ":\n\n"

        for i, record in enumerate(records, 1):
            output += f"{i}. "

            # Try to get name
            name = (
                record.get("Full_Name") or
                record.get("Account_Name") or
                record.get("Deal_Name") or
                record.get("Product_Name") or
                record.get("Subject") or
                "N/A"
            )
            output += f"{name}\n"

            # Add key fields
            if "Email" in record and record["Email"]:
                output += f"   Email: {record['Email']}\n"
            if "Phone" in record and record["Phone"]:
                output += f"   Phone: {record['Phone']}\n"
            if "Company" in record and record["Company"]:
                output += f"   Company: {record['Company']}\n"
            if "Lead_Status" in record:
                output += f"   Status: {record['Lead_Status']}\n"
            if "Stage" in record:
                output += f"   Stage: {record['Stage']}\n"

            output += f"   ID: {record['id']}\n\n"

        return output
