"""
Utility Functions for Zoho CRM MCP Server
Generated by Agent 2 - Base Client Architect

Helper functions used across the application.
"""

import logging
from datetime import datetime
from typing import Any, Dict, Optional
import re

logger = logging.getLogger(__name__)


def format_datetime_for_zoho(date_input: str) -> str:
    """
    Convert various date formats to Zoho CRM datetime format.

    Zoho requires: 'YYYY-MM-DDThh:mm:ss+00:00' (ISO 8601 with UTC timezone)

    Args:
        date_input: Date string in various formats:
            - "2024-01-15" → "2024-01-15T00:00:00+00:00"
            - "2024-01-15 14:30" → "2024-01-15T14:30:00+00:00"
            - "2024-01-15T14:30:00" → "2024-01-15T14:30:00+00:00"

    Returns:
        str: Zoho-formatted datetime string (ISO 8601)

    Examples:
        >>> format_datetime_for_zoho("2024-01-15")
        '2024-01-15T00:00:00+00:00'

        >>> format_datetime_for_zoho("2024-01-15 14:30")
        '2024-01-15T14:30:00+00:00'
    """
    # If already in correct format, return as-is
    if re.match(r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2}$', date_input):
        return date_input

    try:
        # Parse various formats
        if 'T' in date_input:
            # Already has time separator
            if len(date_input) == 19:  # YYYY-MM-DDTHH:MM:SS
                return f"{date_input}+00:00"
            elif len(date_input) == 16:  # YYYY-MM-DDTHH:MM
                return f"{date_input}:00+00:00"
        elif ' ' in date_input:
            # Space-separated date time
            parts = date_input.split(' ')
            if len(parts) == 2:
                date_part, time_part = parts
                if len(time_part) == 5:  # HH:MM
                    return f"{date_part}T{time_part}:00+00:00"
                elif len(time_part) == 8:  # HH:MM:SS
                    return f"{date_part}T{time_part}+00:00"
        else:
            # Just date, add midnight time
            if len(date_input) == 10:  # YYYY-MM-DD
                return f"{date_input}T00:00:00+00:00"

        # If we get here, format wasn't recognized
        logger.warning(f"Unrecognized date format: {date_input}")
        return date_input

    except Exception as e:
        logger.error(f"Error formatting datetime: {e}")
        return date_input


def build_zoho_criteria(conditions: Dict[str, Any]) -> str:
    """
    Build Zoho search criteria from dictionary of conditions.

    Args:
        conditions: Dictionary of field: value or field__operator: value
            Examples:
            {
                "Last_Name": "Smith",                    # equals
                "Email__contains": "@gmail.com",         # contains
                "Created_Time__greater_than": "2024-01-01"  # >
            }

    Returns:
        str: Zoho criteria string like "((Last_Name:equals:Smith)and(Email:contains:@gmail.com))"

    Supported operators:
        - equals (default)
        - contains
        - starts_with
        - not_equal
        - greater_than
        - greater_equal
        - less_than
        - less_equal
        - between (value should be tuple/list of 2 values)
    """
    if not conditions:
        return ""

    criteria_parts = []

    for key, value in conditions.items():
        # Parse field and operator
        if '__' in key:
            field, operator = key.rsplit('__', 1)
        else:
            field, operator = key, 'equals'

        # Handle datetime fields - CRITICAL: format BEFORE building criteria
        if any(time_field in field for time_field in ['Time', 'Date']):
            if operator == 'between' and isinstance(value, (list, tuple)):
                # For between operator with dates, ensure both values have time components
                start_val = str(value[0])
                end_val = str(value[1])

                # Add end-of-day time to end date if it's just a date (YYYY-MM-DD)
                if len(end_val) == 10:  # Just date, no time
                    end_val = f"{end_val}T23:59:59+00:00"
                else:
                    end_val = format_datetime_for_zoho(end_val)

                # Add start-of-day time to start date
                if len(start_val) == 10:  # Just date, no time
                    start_val = f"{start_val}T00:00:00+00:00"
                else:
                    start_val = format_datetime_for_zoho(start_val)

                value = [start_val, end_val]
            else:
                value = format_datetime_for_zoho(str(value))

        # Build criteria part
        if operator == 'between' and isinstance(value, (list, tuple)):
            criteria_parts.append(f"({field}:{operator}:{value[0]},{value[1]})")
        else:
            criteria_parts.append(f"({field}:{operator}:{value})")

    # Combine with 'and'
    if len(criteria_parts) == 1:
        criteria_string = criteria_parts[0]
    else:
        criteria_string = '(' + 'and'.join(criteria_parts) + ')'

    # Log the generated criteria for debugging
    logger.info(f"Generated Zoho criteria: {criteria_string}")
    return criteria_string


def clean_zoho_response(data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Clean and normalize Zoho API response.

    Removes None values and normalizes structure.

    Args:
        data: Raw Zoho API response

    Returns:
        Dict: Cleaned response
    """
    if not isinstance(data, dict):
        return data

    cleaned = {}
    for key, value in data.items():
        if value is None:
            continue

        if isinstance(value, dict):
            cleaned[key] = clean_zoho_response(value)
        elif isinstance(value, list):
            cleaned[key] = [
                clean_zoho_response(item) if isinstance(item, dict) else item
                for item in value
            ]
        else:
            cleaned[key] = value

    return cleaned


def validate_module_name(module: str) -> bool:
    """
    Validate if module name is a standard Zoho CRM module.

    Args:
        module: Module name to validate

    Returns:
        bool: True if valid module
    """
    valid_modules = {
        "Leads", "Contacts", "Accounts", "Deals", "Products",
        "Quotes", "Sales_Orders", "Purchase_Orders", "Invoices",
        "Vendors", "Tasks", "Events", "Calls", "Cases",
        "Solutions", "Campaigns"
    }

    return module in valid_modules


def extract_record_id(response: Dict[str, Any]) -> Optional[str]:
    """
    Extract record ID from Zoho create/update response.

    Args:
        response: Zoho API response

    Returns:
        Optional[str]: Record ID if found, None otherwise
    """
    try:
        if 'data' in response and isinstance(response['data'], list):
            if len(response['data']) > 0:
                record = response['data'][0]
                if 'details' in record and 'id' in record['details']:
                    return record['details']['id']
                elif 'id' in record:
                    return record['id']
    except Exception as e:
        logger.error(f"Error extracting record ID: {e}")

    return None


def format_error_message(response: Dict[str, Any]) -> str:
    """
    Extract and format error message from Zoho API error response.

    Args:
        response: Zoho error response

    Returns:
        str: Formatted error message
    """
    try:
        if 'data' in response and isinstance(response['data'], list):
            if len(response['data']) > 0:
                error = response['data'][0]
                if 'message' in error:
                    code = error.get('code', 'UNKNOWN')
                    message = error['message']
                    return f"[{code}] {message}"

        if 'message' in response:
            return response['message']

        return str(response)

    except Exception:
        return "Unknown error occurred"


def paginate_results(
    total_count: int,
    per_page: int = 200,
    max_pages: Optional[int] = None
) -> list:
    """
    Calculate pagination parameters.

    Args:
        total_count: Total number of records
        per_page: Records per page (max 200 for Zoho)
        max_pages: Maximum pages to fetch (None for all)

    Returns:
        list: List of (page_number, per_page) tuples
    """
    per_page = min(per_page, 200)  # Zoho max
    total_pages = (total_count + per_page - 1) // per_page

    if max_pages:
        total_pages = min(total_pages, max_pages)

    return [(page + 1, per_page) for page in range(total_pages)]
